# Generated by Django 2.2.4 on 2019-08-15 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('time', models.TimeField(auto_created=True, verbose_name='时间')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('descript', models.CharField(max_length=200, verbose_name='简介')),
                ('name', models.CharField(max_length=20, verbose_name='文章名字')),
                ('content', models.TextField(blank=True, null=True, verbose_name='内容')),
            ],
            options={
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Baike',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='百科名')),
                ('content', models.TextField(verbose_name='内容')),
            ],
            options={
                'db_table': 'baike',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('time', models.TimeField(auto_created=True, verbose_name='时间')),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='菜谱名')),
                ('content', models.TextField(verbose_name='内容')),
                ('descript', models.CharField(max_length=200, verbose_name='描述')),
                ('img', models.CharField(blank=True, max_length=255, null=True, verbose_name='图片')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Menutype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=20, verbose_name='菜谱分类')),
            ],
            options={
                'db_table': 'menutype',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='昵称')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='邮箱')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='主题分类名')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Menu', verbose_name='菜谱')),
            ],
            options={
                'db_table': 'theme',
            },
        ),
        migrations.CreateModel(
            name='Shicai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='食材分类名')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Menu', verbose_name='菜谱')),
            ],
            options={
                'db_table': 'shicai',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='其他分类名')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Menu', verbose_name='菜谱')),
            ],
            options={
                'db_table': 'other',
            },
        ),
        migrations.CreateModel(
            name='MenuShouLike',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('love', models.BooleanField(default=False, verbose_name='喜欢')),
                ('collect', models.BooleanField(default=False, verbose_name='收藏')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Menu', verbose_name='菜谱')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'menu_shou_like',
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Menutype', verbose_name='菜谱类型'),
        ),
        migrations.AddField(
            model_name='menu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User', verbose_name='发表人'),
        ),
        migrations.CreateModel(
            name='Foodtype',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='饮食分类名')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Menu', verbose_name='菜谱')),
            ],
            options={
                'db_table': 'foodtype',
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('myid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='myid', to='app.User')),
                ('yid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='yid', to='app.User')),
            ],
            options={
                'db_table': 'follow',
            },
        ),
        migrations.CreateModel(
            name='BaikeShowLike',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('love', models.BooleanField(default=False, verbose_name='喜欢')),
                ('collect', models.BooleanField(default=False, verbose_name='收藏')),
                ('baike', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Baike', verbose_name='百科')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'baike_show_like',
            },
        ),
        migrations.AddField(
            model_name='baike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User', verbose_name='用户'),
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Article', verbose_name='文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User', verbose_name='用户')),
            ],
            options={
                'db_table': 'article_like',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User', verbose_name='作者'),
        ),
    ]
