# Generated by Django 2.2.4 on 2019-08-17 08:32

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, null=True, verbose_name='内容'),
        ),
    ]
