# Generated by Django 2.2.4 on 2019-08-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20190817_0832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.CharField(default='', max_length=255, verbose_name='文章图片'),
            preserve_default=False,
        ),
    ]
