# Generated by Django 2.2.4 on 2019-08-17 08:32

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('find1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baike',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='content',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='time',
            field=models.TimeField(auto_now_add=True, verbose_name='时间'),
        ),
    ]
