# Generated by Django 2.2.4 on 2019-08-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('find1', '0002_auto_20190817_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='baike',
            name='img',
            field=models.CharField(default='', max_length=255, verbose_name='百科图片'),
        ),
    ]
